apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zerossl-eab
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: zerossl-eabsecret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: /infrastructures/pve-talos-clusters/platform-cluster-01/cert-manager/zerossl/eab-hmac-key
