apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: victoria-k8s-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true

  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/lhtran-homelab/infrastructures.git
              revision: master
              files:
                - path: gitops/clusters/*/victoria-k8s-stack/release.yml
          - git:
              repoURL: https://github.com/lhtran-homelab/infrastructures.git
              revision: master
              files:
                - path: "gitops/clusters/{{index .path.segments 2}}/config.yml"

  template:
    metadata:
      name: "{{.cluster.name}}-victoria-k8s-stack"
      labels:
        cluster: "{{.cluster.name}}"
        component: victoria-k8s-stack
    spec:
      project: platform-apps

      sources:
        - repoURL: https://github.com/lhtran-homelab/infrastructures.git
          targetRevision: master
          ref: values

        - repoURL: https://victoriametrics.github.io/helm-charts
          chart: victoria-metrics-k8s-stack
          targetRevision: "{{.release.version}}"
          helm:
            parameters:
              - name: fullnameOverride
                value: vm-stack          
            valueFiles:
              - $values/gitops/defaults/victoria-k8s-stack/values.yml
              - $values/gitops/clusters/{{.cluster.name}}/victoria-k8s-stack/values.yml

        - repoURL: https://github.com/lhtran-homelab/infrastructures.git
          targetRevision: master
          path: "gitops/clusters/{{.cluster.name}}/victoria-k8s-stack/manifests"

      destination:
        name: "{{.destination.name}}"
        namespace: monitoring

      syncPolicy:
        managedNamespaceMetadata:
          labels:
            shared-traefik-gateway-access: "true"
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true
          - FailOnSharedResource=true
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
