global:
  domain: "${hostname}"

configs:
  params:
    server.insecure: true
  cm:
    oidc.config: |
      name: Pocket-ID
      issuer: https://id.lhtran.com
      clientID: fc28022a-b819-49fa-a690-bbbfd4866cc0
      clientSecret: "${argocd_pocketid_client_secret}"
      requestedScopes:
        - openid
        - profile
        - email
        - groups
  rbac:
    scopes: '[groups]'
    policy.csv: |
      g, argocd_admin, role:admin
server:
  service:
    servicePortHttp2: 8085
    servicePortHttp2AppProtocol: "kubernetes.io/h2c"
  httproute:
    enabled: true
    hostnames: 
      - "${hostname}"
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: https-tools
  grpcroute:
    enabled: false
