apiVersion: v1
kind: Service
metadata:
  name: pod-identity-webhook
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app.kubernetes.io/name: pod-identity-webhook
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
