global:
  domain: "${hostname}"

configs:
  params:
    server.insecure: true
  cm:
    oidc.config: |
      name: Pocket-ID
      issuer: $argocd-pocketid-oidc:issuer
      clientID: $argocd-pocketid-oidc:clientID
      clientSecret: $argocd-pocketid-oidc:clientSecret
      requestedScopes:
        - openid
        - profile
        - email
        - groups
  rbac:
    scopes: '[groups]'
    policy.csv: |
      g, argocd_admin, role:admin
server:
  service:
    servicePortHttp2: 8085
    servicePortHttp2AppProtocol: "kubernetes.io/h2c"
  httproute:
    enabled: true
    hostnames: 
      - "${hostname}"
    parentRefs:
      - name: traefik-gateway
        namespace: traefik
        sectionName: https-tools
  grpcroute:
    enabled: false
