apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-ssm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-east-1
      role: arn:aws:iam::734061930556:role/eso-platform-cluster-01
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
