apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-pocketid-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: openbao-pocketid-oidc
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /infrastructures/pve-talos-clusters/platform-cluster-01/openbao/pocketid/client-secret
