apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-pocketid-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: grafana-pocketid-oidc
    creationPolicy: Owner
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: /infrastructures/pve-talos-clusters/platform-cluster-01/grafana/pocketid/client-id
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /infrastructures/pve-talos-clusters/platform-cluster-01/grafana/pocketid/client-secret