apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-pocketid-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: headlamp-pocketid-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: /infrastructures/pve-talos-clusters/platform-cluster-01/headlamp/pocketid/client-id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /infrastructures/pve-talos-clusters/platform-cluster-01/headlamp/pocketid/client-secret
    - secretKey: OIDC_ISSUER_URL
      remoteRef:
        key: /infrastructures/pve-talos-clusters/platform-cluster-01/headlamp/pocketid/issuer
    - secretKey: OIDC_SCOPES
      remoteRef:
        key: /infrastructures/pve-talos-clusters/platform-cluster-01/headlamp/pocketid/scopes